# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-19 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('background_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('verification_code_lvl_1', models.CharField(default='', max_length=64)),
                ('verification_code_lvl_2', models.CharField(default='', max_length=64)),
                ('address', models.CharField(blank=True, default='NA', max_length=64, null=True)),
                ('url', models.CharField(blank=True, default='NA', max_length=64, null=True)),
                ('auth1', models.BooleanField(default=False)),
                ('auth2', models.BooleanField(default=False)),
                ('eth_address', models.CharField(default='Not Setup', max_length=64)),
                ('received_certificates', models.ManyToManyField(blank=True, related_name='received_certificates', to='background_tasks.Certificate')),
                ('sent_certificates', models.ManyToManyField(blank=True, related_name='sent_certificates', to='background_tasks.Certificate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
