# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 02:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=64)),
                ('access_token', models.CharField(max_length=64)),
                ('transaction_time', models.DateTimeField()),
                ('transaction_amount', models.FloatField()),
                ('receiver', models.CharField(max_length=64)),
                ('validity', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='awarding_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web_portal.UserProfile'),
        ),
    ]
