# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='certificate',
            field=models.ImageField(blank=True, upload_to='certificates'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
