# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web_portal', '0002_auto_20180220_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='awarding_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
