# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web_portal', '0003_auto_20180220_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='awarding_organization',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
