# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-24 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web_portal', '0005_auto_20180324_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='url',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verification_code_lvl_1',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verification_code_lvl_2',
            field=models.CharField(default='', max_length=64),
        ),
    ]
