# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web_portal', '0006_auto_20180324_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auth2',
            field=models.BooleanField(default=False),
        ),
    ]
