# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web_portal', '0008_userprofile_eth_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='eth_address',
            field=models.CharField(default='Not Setup', max_length=64),
        ),
    ]
