# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-09 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web_portal', '0009_auto_20180405_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedCertificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.IntegerField(unique=True)),
                ('receiver_address', models.CharField(max_length=50)),
                ('receiver_proof', models.CharField(max_length=500)),
                ('sender_address', models.CharField(max_length=50)),
                ('sender_proof', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('create_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SentCertificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.IntegerField(unique=True)),
                ('receiver_address', models.CharField(max_length=50)),
                ('receiver_proof', models.CharField(max_length=500)),
                ('sender_address', models.CharField(max_length=50)),
                ('sender_proof', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('create_time', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='received_cert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_web_portal.ReceivedCertificates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sent_cert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_web_portal.SentCertificates'),
            preserve_default=False,
        ),
    ]
