# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-09 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_web_portal', '0010_auto_20180409_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='received_cert',
            field=models.ForeignKey(blank=True, db_column='receivedCerts', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_web_portal.ReceivedCertificates'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sent_cert',
            field=models.ForeignKey(blank=True, db_column='sentCerts', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_web_portal.SentCertificates'),
        ),
    ]
