# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.IntegerField(unique=True),
        ),
    ]
